# Generated by Django 6.0.5 on 2026-05-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caso', models.CharField(max_length=50, verbose_name='Número de Caso')),
                ('cliente', models.CharField(max_length=200)),
                ('materia', models.CharField(choices=[('Civil', 'Civil'), ('Familiar', 'Familiar'), ('Laboral', 'Laboral'), ('Penal', 'Penal')], default='Civil', max_length=50)),
                ('juzgado', models.CharField(blank=True, max_length=100, null=True)),
                ('abogado_asignado', models.CharField(max_length=200, verbose_name='Abogado Asignado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Caso')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Trámite', 'Trámite'), ('Archivado', 'Archivado')], default='Activo', max_length=20)),
            ],
        ),
    ]
