# Generated by Django 6.0.5 on 2026-05-20 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('abogado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Abogado asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(blank=True, max_length=50, verbose_name='N° de expediente')),
                ('nurej', models.CharField(blank=True, max_length=50, verbose_name='NUREJ')),
                ('juzgado', models.CharField(blank=True, max_length=200, verbose_name='Juzgado')),
                ('materia', models.CharField(choices=[('Civil', 'Civil'), ('Penal', 'Penal'), ('Familia', 'Familia'), ('Laboral', 'Laboral'), ('Administrativo', 'Administrativo'), ('Constitucional', 'Constitucional'), ('Otro', 'Otro')], default='Civil', max_length=50, verbose_name='Materia')),
                ('tipo_proceso', models.CharField(blank=True, max_length=100, verbose_name='Tipo de proceso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del caso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('concluido', 'Concluido'), ('archivado', 'Archivado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_conclusion', models.DateField(blank=True, null=True, verbose_name='Fecha de conclusión')),
                ('activo', models.BooleanField(default=True)),
                ('abogado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to=settings.AUTH_USER_MODEL, verbose_name='Abogado responsable')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='control_legal.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del documento')),
                ('tipo', models.CharField(choices=[('demanda', 'Demanda'), ('contestacion', 'Contestación'), ('resolucion', 'Resolución judicial'), ('memorial', 'Memorial'), ('contrato', 'Contrato'), ('poder', 'Poder notarial'), ('prueba', 'Prueba / evidencia'), ('notificacion', 'Notificación'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to='expedientes/%Y/%m/', verbose_name='Archivo (PDF/imagen)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='control_legal.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiencia'), ('resolucion', 'Resolución'), ('notificacion', 'Notificación'), ('memorial', 'Memorial presentado'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo')),
                ('fecha', models.DateField(verbose_name='Fecha del movimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control_legal.expediente', verbose_name='Expediente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
