# Generated by Django 6.0.5 on 2026-05-20 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiencia'), ('entrevista', 'Entrevista con cliente'), ('seguimiento', 'Seguimiento de proceso'), ('otro', 'Otro')], default='audiencia', max_length=20)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar / sala')),
                ('enlace_virtual', models.URLField(blank=True, verbose_name='Enlace virtual (Meet/Zoom)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / notas')),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='control_legal.expediente', verbose_name='Expediente relacionado')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Agenda',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
