# Generated by Django 6.0.5 on 2026-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='nurej',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NUREJ'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Trámite', 'Trámite'), ('Concluido', 'Concluido')], default='Activo', max_length=20),
        ),
    ]
