# Generated by Django 6.0.5 on 2026-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0002_caso_nurej_alter_caso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
