# Generated by Django 6.0.5 on 2026-05-21 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0003_tarea_evidenciatarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('tipo', models.CharField(choices=[('honorarios', 'Contrato de honorarios profesionales'), ('poder_notarial', 'Poder notarial'), ('arrendamiento', 'Contrato de arrendamiento'), ('compraventa', 'Contrato de compraventa'), ('confidencialidad', 'Acuerdo de confidencialidad'), ('otro', 'Otro')], default='honorarios', max_length=30)),
                ('contenido', models.TextField(help_text='Usa estas variables: {{cliente_nombre}}, {{cliente_ci}}, {{cliente_direccion}}, {{abogado_nombre}}, {{fecha_hoy}}, {{expediente_nurej}}, {{monto}}, {{ciudad}}', verbose_name='Contenido de la plantilla')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de contrato',
                'verbose_name_plural': 'Plantillas de contratos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del contrato')),
                ('contenido_final', models.TextField(verbose_name='Contenido final del contrato')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto (Bs.)')),
                ('ciudad', models.CharField(default='La Paz', max_length=100, verbose_name='Ciudad')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='control_legal.cliente', verbose_name='Cliente')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='control_legal.expediente', verbose_name='Expediente relacionado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados', to='control_legal.plantillacontrato', verbose_name='Plantilla usada')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
