# Generated by Django 6.0.5 on 2026-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0004_plantillacontrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Código de acceso del cliente'),
        ),
    ]
