# Generated by Django 6.0.5 on 2026-05-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0005_cliente_codigo_acceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMemorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Demanda de Asistencia Familiar', max_length=200, verbose_name='Nombre del memorial')),
                ('categoria', models.CharField(choices=[('asistencia_familiar', 'Asistencia Familiar'), ('civil', 'Civil'), ('penal', 'Penal'), ('laboral', 'Laboral'), ('constitucional', 'Constitucional'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], default='civil', max_length=30, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Explica cuándo se usa este memorial', verbose_name='Descripción breve')),
                ('estructura', models.TextField(help_text='Escribe aquí la estructura que la IA debe seguir. Puedes incluir las secciones obligatorias, el tono, las normas legales aplicables y los datos que debe pedir. Variables disponibles: {{cliente_nombre}}, {{cliente_ci}}, {{expediente_nurej}}, {{juzgado}}, {{abogado_nombre}}, {{ciudad}}, {{fecha_hoy}}', verbose_name='Estructura / molde del memorial')),
                ('normas_aplicables', models.TextField(blank=True, help_text='Ej: Art. 109 Código de Familia, Art. 5 Ley 603', verbose_name='Normas legales aplicables')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_memorial_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de memorial',
                'verbose_name_plural': 'Plantillas de memoriales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del memorial')),
                ('contenido_final', models.TextField(verbose_name='Contenido generado')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memoriales', to='control_legal.cliente', verbose_name='Cliente')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoriales', to='control_legal.expediente', verbose_name='Expediente relacionado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoriales_generados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoriales_generados', to='control_legal.plantillamemorial', verbose_name='Plantilla usada')),
            ],
            options={
                'verbose_name': 'Memorial',
                'verbose_name_plural': 'Memoriales',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
