# Generated by Django 6.0.5 on 2026-05-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_legal', '0006_plantillamemorial_memorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecedenteJurisprudencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribunal', models.CharField(choices=[('tcp', 'Tribunal Constitucional Plurinacional (TCP)'), ('tsj', 'Tribunal Supremo de Justicia (TSJ)'), ('otro', 'Otro tribunal')], default='tcp', max_length=10, verbose_name='Tribunal')),
                ('tipo_resolucion', models.CharField(choices=[('scp', 'Sentencia Constitucional Plurinacional (SCP)'), ('sc', 'Sentencia Constitucional (SC)'), ('as', 'Auto Supremo (AS)'), ('ac', 'Auto Constitucional (AC)'), ('dcp', 'Declaración Constitucional Plurinacional (DCP)'), ('otro', 'Otro')], default='scp', max_length=10, verbose_name='Tipo de resolución')),
                ('numero_sentencia', models.CharField(help_text='Ej: 0732/2023-S2 o AS 234/2021', max_length=50, unique=True, verbose_name='Número de sentencia')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('materia', models.CharField(choices=[('civil', 'Civil'), ('penal', 'Penal'), ('familia', 'Familia'), ('laboral', 'Laboral'), ('constitucional', 'Constitucional'), ('administrativo', 'Administrativo'), ('tributario', 'Tributario'), ('asistencia_familiar', 'Asistencia Familiar'), ('derechos_humanos', 'Derechos Humanos'), ('otro', 'Otro')], default='civil', max_length=30, verbose_name='Materia')),
                ('magistrado_relator', models.CharField(blank=True, max_length=200, verbose_name='Magistrado relator')),
                ('sala', models.CharField(blank=True, help_text='Ej: Primera Sala, Sala Civil', max_length=100, verbose_name='Sala / Comisión')),
                ('accion_origen', models.CharField(blank=True, help_text='Ej: Acción de Amparo Constitucional, Recurso de Casación', max_length=200, verbose_name='Acción de origen')),
                ('palabras_clave', models.TextField(blank=True, help_text='Separadas por coma. Ej: debido proceso, tutela, presunción de inocencia', verbose_name='Palabras clave')),
                ('ratio_decidendi', models.TextField(blank=True, help_text='La regla jurídica central que establece la sentencia', verbose_name='Ratio Decidendi')),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen automático del holding y su aplicación práctica', verbose_name='Resumen generado por IA')),
                ('texto_completo', models.TextField(blank=True, verbose_name='Texto completo de la sentencia')),
                ('url_fuente', models.URLField(blank=True, help_text='Link directo a la sentencia en el sitio oficial', verbose_name='URL fuente (TCP/TSJ)')),
                ('origen', models.CharField(choices=[('scraper', 'Extraído automáticamente (bot)'), ('manual', 'Ingresado manualmente'), ('ia', 'Generado/completado por IA')], default='manual', max_length=10, verbose_name='Origen del registro')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado por abogado')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ingresado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedentes_ingresados', to=settings.AUTH_USER_MODEL, verbose_name='Ingresado por')),
            ],
            options={
                'verbose_name': 'Precedente jurisprudencial',
                'verbose_name_plural': 'Banco de jurisprudencia',
                'ordering': ['-fecha_resolucion', 'numero_sentencia'],
                'indexes': [models.Index(fields=['numero_sentencia'], name='control_leg_numero__f1282d_idx'), models.Index(fields=['materia'], name='control_leg_materia_b458d0_idx'), models.Index(fields=['tribunal'], name='control_leg_tribuna_770c33_idx'), models.Index(fields=['fecha_resolucion'], name='control_leg_fecha_r_cd94a8_idx')],
            },
        ),
    ]
